### ISSUE TITLE
能连接成功，但获取balance等都是timeout

### ISSUE THREAD

**Issue by 0JustinTang0** [Tu5039/THSTrader#3]
正在连接客户端: C:\同花顺软件\同花顺\xiadan.exe ......
连接成功!!!
timed out
timed out
timed out
timed out
timed out
timed out
timed out
timed out
timed out
timed out
timed out
timed out

**Comment by Tu5039** [comment]
是否是没有打开下单，或者是交易窗口被最小化了？

**Comment by 0JustinTang0** [comment]
下单软件窗口是前置的，我这边用的是银河证券，同花顺版本8.80.61

**Comment by Tu5039** [comment]
那可能要用看一下库源码的调用是否出了问题，可以用spy++看一下交易窗口的id是否与库源码的不同。

**Comment by 0JustinTang0** [comment]
HSTrader-master\THS\THSTrader.py", line 174, in __get_left_menus_handle
    handle.wait('ready', 2)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\pywinauto\application.py", line 501, in wait
    lambda: self.__check_all_conditions(check_method_names, retry_interval))
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\pywinauto\timings.py", line 362, in wait_until
    time.sleep(min(retry_interval, time_left))

**Comment by linhua55** [comment]
后端改用`uia`
pywinauto.Application(backend="uia").connect(path=exe_path, timeout=10)

**Comment by shijie2016** [comment]
改uia之后不会报time out, 但是会有新的错误：
`正在连接客户端: C:\同花顺软件\同花顺\xiadan.exe ......
连接成功!!!
Traceback (most recent call last):
  File "testTHS.py", line 10, in <module>
    print(trader.get_position())                           # 获取当前持有的股票
  File "C:\SynologyDrive\Code\more_money\THSTrader\THS\THSTrader.py", line 73, in get_position
    self.__select_menu(['查询[F4]', '资金股票'])
  File "C:\SynologyDrive\Code\more_money\THSTrader\THS\THSTrader.py", line 166, in __select_menu
    self.__get_left_menus_handle().get_item(path).click()
AttributeError: 'TreeItemWrapper' object has no attribute 'click'`
